security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging: # <----New sections below
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote

spring: # <---NEW SECTION
  cloud:
    services:
      registrationMethod: direct
  
ribbon: # <---NEW SECTION
  IsSecure: false
