security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging: # <----New sections below
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true
  swagatatesting: Hi there!

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
